name: flutter_time_duration_picker_example
description: Example app for flutter_time_duration_picker package

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # For local development, reference the parent directory
  flutter_time_duration_picker:
    path: ../

  # Once published, you would use this instead:
  # flutter_time_duration_picker: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true